name: Dependency update
inputs:
  list-of-deps:
    required: true
    default: ''

runs:
  using: 'composite'
  runs-on: ubuntu-latest
  steps:
    - name: Update deps
      run: sudo apt-get update
    - name: Install deps
      run: sudo apt-get -y install ${{ inputs.list-of-deps }}
