name: Dependency update

runs:
  using: 'composite'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
    - uses: actions/setup-node@v4
      with:
        node-version: '20.14.0'
    - name: Update deps
      run: sudo apt-get update
