module.exports = [
  './node_modules/fundamental-styles/dist/variables.css',
  './node_modules/fundamental-styles/dist/icon.css',
  './node_modules/fundamental-styles/dist/layout.css',
  './node_modules/fundamental-styles/dist/action-bar.css',
  // './node_modules/fundamental-styles/dist/alert.css',
  //'./node_modules/fundamental-styles/dist/file-uploader.css',
  //'./node_modules/fundamental-styles/dist/avatar.css',
  //'./node_modules/fundamental-styles/dist/badge.css',
  './node_modules/fundamental-styles/dist/bar.css',
  //'./node_modules/fundamental-styles/dist/breadcrumb.css',
  './node_modules/fundamental-styles/dist/busy-indicator.css',
  './node_modules/fundamental-styles/dist/button.css',
  //'./node_modules/fundamental-styles/dist/button-split.css',
  //'./node_modules/fundamental-styles/dist/calendar.css',
  // './node_modules/fundamental-styles/dist/checkbox.css',
  './node_modules/fundamental-styles/dist/counter.css',
  './node_modules/fundamental-styles/dist/dialog.css',
  //'./node_modules/fundamental-styles/dist/fieldset.css',
  //'./node_modules/fundamental-styles/dist/form-group.css',
  //'./node_modules/fundamental-styles/dist/form-item.css',
  //'./node_modules/fundamental-styles/dist/form-label.css',
  //'./node_modules/fundamental-styles/dist/form-message.css',
  //'./node_modules/fundamental-styles/dist/form-select.css',
  //'./node_modules/fundamental-styles/dist/inline-help.css',
  './node_modules/fundamental-styles/dist/input.css',
  './node_modules/fundamental-styles/dist/input-group.css',
  //'./node_modules/fundamental-styles/dist/info-label.css',
  //'./node_modules/fundamental-styles/dist/layout-grid.css',
  //'./node_modules/fundamental-styles/dist/layout-panel.css',
  './node_modules/fundamental-styles/dist/link.css',
  //'./node_modules/fundamental-styles/dist/list.css',
  //'./node_modules/fundamental-styles/dist/localization-editor.css',
  './node_modules/fundamental-styles/dist/menu.css',
  //'./node_modules/fundamental-styles/dist/message-box.css',
  './node_modules/fundamental-styles/dist/message-strip.css',
  //'./node_modules/fundamental-styles/dist/message-toast.css',
  //'./node_modules/fundamental-styles/dist/notification.css',
  //'./node_modules/fundamental-styles/dist/numeric-content.css',
  //'./node_modules/fundamental-styles/dist/object-status.css',
  './node_modules/fundamental-styles/dist/page.css',
  //'./node_modules/fundamental-styles/dist/pagination.css',
  //'./node_modules/fundamental-styles/dist/panel.css',
  './node_modules/fundamental-styles/dist/popover.css',
  './node_modules/fundamental-styles/dist/product-switch.css',
  // './node_modules/fundamental-styles/dist/radio.css',
  //'./node_modules/fundamental-styles/dist/section.css',
  //'./node_modules/fundamental-styles/dist/segmented-button.css',
  // './node_modules/fundamental-styles/dist/select.css',
  './node_modules/fundamental-styles/dist/shellbar.css',
  './node_modules/fundamental-styles/dist/side-nav.css',
  // './node_modules/fundamental-styles/dist/switch.css',
  //'./node_modules/fundamental-styles/dist/step-input.css'
  //'./node_modules/fundamental-styles/dist/table.css',
  './node_modules/fundamental-styles/dist/tabs.css',
  // './node_modules/fundamental-styles/dist/textarea.css',
  //'./node_modules/fundamental-styles/dist/tile.css',
  //'./node_modules/fundamental-styles/dist/time.css',
  //'./node_modules/fundamental-styles/dist/title.css',
  //'./node_modules/fundamental-styles/dist/token.css',
  //'./node_modules/fundamental-styles/dist/tokenizer.css',
  //'./node_modules/fundamental-styles/dist/toolbar.css',
  //'./node_modules/fundamental-styles/dist/tree.css',
  './node_modules/fundamental-styles/dist/helpers.css'
];
