on:   
  # Triggers this action every Monday (1) at 6:00 o'clock. Explanation: https://dev.to/anshuman_bhardwaj/free-cron-jobs-with-github-actions-31d6 
  schedule:
    - cron: "0 6 * * 1"

jobs:
  trigger-script-test:
    name: Trigger script tests on travis
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST -d "{\"request\":{\"branch\":\"master\", \"message\":\"test-setup-scripts\"}}" -H "Content-Type:application/json" -H "Accept:application/json" -H "Travis-API-Version:3" -H "Authorization:token ${{ secrets.TRAVIS }}" https://api.travis-ci.com/repo/sap%2Fluigi/requests
