on:
  push:
    branches:
      - 'main'

name: Whitesource Scan

jobs:
  whitesource:
    name: Mend (Whitesource) Scan
    runs-on: ubuntu-latest
    env:
      WHITESOURCE_APIKEY: ${{ secrets.WHITESOURCE_APIKEY }}
      WHITESOURCE_BASEURL: ${{ secrets.WHITESOURCE_BASEURL }}
      WHITESOURCE_PRODUCT_TOKEN: ${{ secrets.WHITESOURCE_PRODUCT_TOKEN }}
      WHITESOURCE_USER_TOKEN: ${{ secrets.WHITESOURCE_USER_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
      - uses: actions/cache@v4
        with:
          path: ~/.cache
          key: whitesource_cache-${{ github.ref }}
      - run: npm --prefix ./client ci ./client
      - run: npm --prefix ./core ci ./core
      - run: npm --prefix ./website/landingpage/dev install ./website/landingpage/dev
      - run: npm --prefix ./website/fiddle install ./website/fiddle
      - run: npm --prefix ./plugins ci ./plugins
      - run: npm --prefix ./container ci ./container
      - run: npm --prefix ./client-frameworks-support/client-support-ui5 ci ./client-frameworks-support/client-support-ui5
      - run: npm --prefix ./client-frameworks-support/client-support-angular ci ./client-frameworks-support/client-support-angular
      - run: npm --prefix ./client-frameworks-support/testing-utilities ci ./client-frameworks-support/testing-utilities
      - run: bash ./scripts/whiteSource.sh