on:
  workflow_call:
    inputs:
      buildcache_key:
        type: string
        required: true

name: Dependency check

jobs:
  update:
    name: Update deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
      - run: sudo apt-get update
